# Generated by Django 3.0.4 on 2020-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Publication_Date', models.DateField()),
                ('Body', models.TextField()),
                ('Images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
